version: '3.8'

services:
  postgres_db1:
    image: postgres:15
    container_name: postgres_db1
    environment:
      POSTGRES_USER: user1
      POSTGRES_PASSWORD: password1
      POSTGRES_DB: db1
    ports:
      - "5432:5432"
    volumes:
      - postgres_db1_data:/var/lib/postgresql/data

  postgres_db2:
    image: postgres:15
    container_name: postgres_db2
    environment:
      POSTGRES_USER: user2
      POSTGRES_PASSWORD: password2
      POSTGRES_DB: db2
    ports:
      - "5433:5432"
    volumes:
      - postgres_db2_data:/var/lib/postgresql/data
      
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5051:80"

volumes:
  postgres_db1_data:
  postgres_db2_data:
